#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-xlib
Version  : 0.31
Release  : 1
URL      : https://files.pythonhosted.org/packages/40/9c/107e22f637d33434404c07d69112b9d26b76ee0dd4dd705131ab6cdcc818/python-xlib-0.31.tar.gz
Source0  : https://files.pythonhosted.org/packages/40/9c/107e22f637d33434404c07d69112b9d26b76ee0dd4dd705131ab6cdcc818/python-xlib-0.31.tar.gz
Summary  : Python X Library
Group    : Development/Tools
License  : LGPL-2.1+
Requires: python-xlib-python = %{version}-%{release}
Requires: python-xlib-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
====================
        
        |Build Status| |codecov.io| |Code Health|
        
        `Homepage`_ | `Releases`_ | `Changelog`_
        
        Copyright
        ~~~~~~~~~
        
        The main part of the code is

%package python
Summary: python components for the python-xlib package.
Group: Default
Requires: python-xlib-python3 = %{version}-%{release}

%description python
python components for the python-xlib package.


%package python3
Summary: python3 components for the python-xlib package.
Group: Default
Requires: python3-core
Provides: pypi(python_xlib)
Requires: pypi(six)

%description python3
python3 components for the python-xlib package.


%prep
%setup -q -n python-xlib-0.31
cd %{_builddir}/python-xlib-0.31

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635871886
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
